version: '3.0'
services: 
    redis:
        container_name: redis-server
        image: redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports: 
            - 6379:6379
        networks: 
            - microservice

    app_subscribe_01:
        build: db-pubsub/
        # restart: always
        depends_on: 
            - "redis"
        environment: 
            - CHANNEL=CH1
        networks: 
            - microservice

    app_subscribe_02:
        build: db-pubsub/
        # restart: always
        depends_on: 
            - "redis"
        environment: 
            - CHANNEL=CH2
        networks: 
            - microservice

    app_subscribe_03:
        build: db-pubsub/
        # restart: always
        depends_on: 
            - "redis"
        environment: 
            - CHANNEL=CH3
        networks: 
            - microservice

networks: 
    microservice:
        external: 
            name: microservices_network
    